### ISSUE TITLE
Velum does not start if release image is used without '--vanilla' option

### ISSUE THREAD

**Issue by jvanz** [kubic-project/automation#573]
When a cluster is built with the following command:

`./caasp-devenv --build --image channel://release`

The velum does not work. The step which waits Velum to start, fails.
However, when the cluster is build successfully with the `--vanilla` option velum works fine.

**Comment by stefsuse** [comment]
This is expected behavior. The development environment is designed to inject modified velum code, and by default it fetches the latest image, so compatibility is usually not an issue. 

What you did was request a release image, which is defined as V3 (see https://github.com/kubic-project/automation/blob/master/misc-files/download-urls.json), and you injected the latest velum code which is considered v4 beta. --vanilla will use only assets from the build service which is why it worked.

**Comment by jvanz** [comment]
I see. So, if I wanna a CaaSP 3.0 cluster, do I need to checkout the `release-3.0` branch and use the `--vanilla` option?

**Comment by stefsuse** [comment]
Yes that should work.

**Comment by jvanz** [comment]
Ok. Thanks!
